---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role hive
# 

HIVE_VERSION: 1.2.1
# This should match the value for SQOOP_MYSQL_CONNECTOR_VERSION in sqoop role.
HIVE_MYSQL_CONNECTOR_VERSION: 5.1.29
HIVE_HOME: "{{ HADOOP_COMMON_USER_HOME }}/hive"
HIVE_CONF: "{{ HIVE_HOME }}/conf"
HIVE_LIB: "{{ HIVE_HOME }}/lib"

HIVE_METASTORE_DATABASE_NAME: edx_hive_metastore
HIVE_METASTORE_DATABASE:
  user: edx_hive
  password: edx
  name: "{{ HIVE_METASTORE_DATABASE_NAME }}"
  host: 127.0.0.1
  port: 3306


#
# vars are namespace with the module name.
#
hive_role_name: hive
hive_temporary_dir: /var/tmp
hive_dist:
  filename: "apache-hive-{{ HIVE_VERSION }}-bin.tar.gz"
  url: "https://archive.apache.org/dist/hive/hive-{{ HIVE_VERSION }}/apache-hive-{{ HIVE_VERSION }}-bin.tar.gz"
  sha256sum: 29d9780c4af887ef623bafe6a73ec6f1bea9759bbe31fb4aeeb5b0f68c4c9979
  untarred_filename: "apache-hive-{{ HIVE_VERSION }}-bin"
hive_mysql_connector_dist:
  filename: "mysql-connector-java-{{ HIVE_MYSQL_CONNECTOR_VERSION }}.tar.gz"
  url: "http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ HIVE_MYSQL_CONNECTOR_VERSION }}.tar.gz"
  sha256sum: 04ad83b655066b626daaabb9676a00f6b4bc43f0c234cbafafac1209dcf1be73
  untarred_filename: "mysql-connector-java-{{ HIVE_MYSQL_CONNECTOR_VERSION }}"
  jarfilename: "mysql-connector-java-{{ HIVE_MYSQL_CONNECTOR_VERSION }}-bin.jar"

#
# OS packages
#

hive_debian_pkgs: []

hive_redhat_pkgs: []
